apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-tracking-frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issue-tracking-frontend
  template:
    metadata:
      labels:
        app: issue-tracking-frontend
    spec:
      containers:
      - name: issue-tracking-frontend-pod
        image: 475640621870.dkr.ecr.us-east-1.amazonaws.com/issue-tracking-ecr-repo:build-657a8e1d-26e1-45df-840a-561285f211c9
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
