apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-tracking-frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issue-tracking-frontend
  template:
    metadata:
      labels:
        app: issue-tracking-frontend
    spec:
      containers:
      - name: issue-tracking-frontend-pod
        image: 475640621870.dkr.ecr.us-east-1.amazonaws.com/issue-tracking-ecr-repo:build-9fc53959-e307-4eac-b4c8-613832a4fe6e
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
