apiVersion: v1
kind: Service
metadata:
  name: issue-tracking-frontend-svc
  labels:
    app: issue-tracking-frontend
spec:
  type: NodePort
  ports:
  - port: 8100
    nodePort: 30001
    protocol: TCP
  selector:
    app: issue-tracking-frontend
